### PR TITLE
#165177125 users should be able to read articles

### PR DESCRIPTION
**Pull request by richien**
#### What does this PR do?

Adds the endpoints that enable reading of single and multiple articles

#### Description of Task to be completed?

- Added the endpoint that returns a list of all articles in the
database with the most recently added returned first.
- Added the endpoint to return a single article using a slug url

#### How should this be manually tested?

- After cloning this repository, create a virtual environment from the requirements file and change to this branch.
- After setting up the environment variables as specified in the `example.env` file, run the migrations then start the development server.
- In a rest client of your choice, register with the application and create articles. Refer to the README file for a description of the request body.
- You can now call the endpoint `/api/articles/` with a `GET` request to retrieve a list of all your articles with the most recently created returned first. Note that authentication is optional.
- Below is a sample request and response.
**Request**
`GET` `http://localhost:8000/api/articles/` 
**Response**
```
{ "articles":    [
         {
            "slug": "late-show-dinners-1",
            "title": "late show dinners",
            "description": "Lorem Ipsum",
            "body": "What is Lorem Ipsum?Lorem Ipsum is simply dummy text of the
                       printing and typesetting industry. Lorem Ipsum has been 
                       the industry's standard dummy",
            "created_at": "2019-04-12T07:11:26.277872Z",
            "updated_at": "2019-04-12T07:11:26.278301Z",
            "favorited": false,
            "favorites_count": 0,
            "read_time": "1 min read",
            "author": 16
        },
        {
            "slug": "late-show-dinners",
            "title": "late show dinners",
            "description": "Lorem Ipsum",
            "body": "What is Lorem Ipsum?Lorem Ipsum is simply dummy text of the
                       printing and typesetting industry. Lorem Ipsum has been 
                       the industry's standard dummy",
            "created_at": "2019-04-12T07:10:13.426804Z",
            "updated_at": "2019-04-12T07:10:13.426851Z",
            "favorited": false,
            "favorites_count": 0,
            "read_time": "1 min read",
            "author": 16
        }
    ],
    "articlesCount": 2
}
```

- You can also call the endpoint `/api/articles/<str:slug>` with a `GET` request to retrieve a single article based on its slug as below;
**Request**
`GET` `http://localhost:8000/api/articles/late-show-dinners/` 
**Response**
```
{
    "article": {
        "slug": "late-show-dinners",
        "title": "late show dinners",
        "description": "Lorem Ipsum",
        "body": "What is Lorem Ipsum?Lorem Ipsum is simply dummy text of the
                       printing and typesetting industry. Lorem Ipsum has been 
                       the industry's standard dummy",
        "created_at": "2019-04-12T07:10:13.426804Z",
        "updated_at": "2019-04-12T07:10:13.426851Z",
        "favorited": false,
        "favorites_count": 0,
        "read_time": "1 min read",
        "author": 16
    }
}
```
- If no records are found, the following responses are returned when getting articles
**Response for single article**
```
{
    "errors": {
        "detail": "Not found."
    }
}
```
  **Response for multiple articles**
```
{
    "articles" : [],
    "articlesCount": 0
}
```
#### Any background context you want to provide?

- The name of the view `CreateArticlesApiView` is changed to `ArticlesApiView`. This is because the
endpoint `/api/articles/` is expected to receive both `GET` and `POST` requests, ie it is used for reading as well as creating articles. Therefore this change was done to improve the **readability** of that feature.
- Since there is no profile model on the base branch, the response returned. contains an author's ID rather than their profile. This is to be implemented once the profile model becomes available on `develop`.

#### What are the relevant pivotal tracker stories?

[#165177125](https://www.pivotaltracker.com/story/show/165177125)

### CODE REVIEW

**Review by NicholusMuwonge — APPROVED** [review]
@richien This is good but , I do think itd have been nice to allow an empty field thats nullable for readtime for that time it will be merged into the whole project. Reader needs to see that info .

**Review by NicholusMuwonge — CHANGES_REQUESTED** [review]
Sorry I approved instead I was requesting for some of those changes

**Comment by richien** [comment]
> 
> 
> @richien This is good but , I do think itd have been nice to allow an empty field thats nullable for readtime for that time it will be merged into the whole project. Reader needs to see that info .

Thank you for the feedback. The serializers are set to serialize all the article fields in the response. The reason readtime is not in the response is because it it not a field in the Article model on this branch. Once the readtime feature has been added to `develop` and this branch is rebased with `develop`, readtime will also appear in the response.

**Review by NicholusMuwonge — APPROVED** [review]
I have reviewed the code and I have no reason to object and I also found the routes functioning properly as expected . Thanks for the good work @richien

**Review by RonKbS — APPROVED** [review]

**Pull request merged**
